# Filesystem Consolidation After Hermes Version Upgrade

## Context

Detected August 2026: After updating Hermes from v0.10.0 to v0.20.0 (code moved from `/root/hermes-agent/` to `/opt/hermes/`), the Docker container kept running with OLD volume mounts pointing to `/root/hermes-agent/data/` which NO LONGER EXISTS. This caused:

- 5 config.yaml files with different content
- 2 Engram databases diverging
- 6 SOUL.md files with conflicting content
- 4 USER.md files desynchronized

## Audit Procedure

When deploying Hermes on a new server or after a major upgrade:

```bash
# 1. Map Docker mounts
docker inspect <container-id> --format '{{range .Mounts}}{{.Source}} → {{.Destination}}{{"\n"}}{{end}}'

# 2. Verify every Source path EXISTS on host
for mount_path in $(docker inspect <id> --format '{{range .Mounts}}{{.Source}}{{"\n"}}{{end}}'); do
  [ -e "$mount_path" ] || echo "MISSING: $mount_path"
done

# 3. Count duplicate files
find / -name 'config.yaml' 2>/dev/null | grep -v node_modules | grep -v __pycache__
find / -name 'SOUL.md' 2>/dev/null | grep -v node_modules
find / -name 'USER.md' 2>/dev/null | grep -v node_modules
find / -name 'engram.db' 2>/dev/null

# 4. Verify docker-compose.yml matches actual mounts
# Compare docker inspect output against the compose file
```

## Unifying Duplicated Files

### Engram DB (CRITICAL - data loss risk)

```bash
# Checkpoint WAL on the more complete DB first
sqlite3 /opt/data/home/.engram/engram.db 'PRAGMA wal_checkpoint(FULL);'

# Copy the more complete DB to canonical location
cp /opt/data/home/.engram/engram.db /opt/data/.engram/engram.db

# Verify integrity
sqlite3 /opt/data/.engram/engram.db 'PRAGMA integrity_check;'

# Fix permissions
chown -R hermes:hermes /opt/data/.engram/
chmod 644 /opt/data/.engram/engram.db

# Update ENGRAM_DATA_DIR env var in docker-compose.yml
# Remove duplicate
rm -rf /opt/data/home/.engram/
```

### SOUL.md

```bash
# Choose ONE canonical file (usually /opt/data/SOUL.md)
# Verify content says "NeuralCrew Labs" not "Nexa Labs"
sed -i 's/Nexa Labs/NeuralCrew Labs/g' /opt/data/SOUL.md

# Delete all duplicates
rm /opt/data/brain/SOUL.md /opt/data/.hermes/SOUL.md /opt/data/home/.hermes/SOUL.md
rm /opt/data/home/gdrive_files/SOUL.md /opt/data/profiles/coder/SOUL.md
```

### USER.md

```bash
# Keep the most complete version
# Delete duplicates
rm /opt/data/brain/USER.md /opt/data/memories/USER.md /opt/data/home/gdrive_files/USER.md
```

### config.yaml

- Keep ONLY `/opt/data/config.yaml` as canonical
- `/opt/data/home/.hermes/config.yaml` (generated by gentle-ai sync) should only contain MCP config
- If it has more content, merge the MCP section into the canonical
- `/opt/data/profiles/coder/config.yaml` is valid as a separate profile config

## Post-Consolidation Verification

```bash
echo "=== Config count ==="
find / -name 'config.yaml' 2>/dev/null | grep -v node_modules | grep -v __pycache__ | wc -l
echo "=== SOUL count ==="
find / -name 'SOUL.md' 2>/dev/null | grep -v node_modules | wc -l
echo "=== Engram count ==="
find / -name 'engram.db' 2>/dev/null | wc -l
echo "=== Stale mounts ==="
docker inspect <id> --format '{{range .Mounts}}{{.Source}}{{"\n"}}{{end}}' | while read m; do
  [ -e "$m" ] || echo "STALE: $m"
done
```

## Post-Deployment Cleanup (Space Recovery)

| Directory | Typical Size | Action |
|-----------|-------------|--------|
| `.cache/` (pip/npm) | ~2.2 GB | `pip cache purge && npm cache clean --force` |
| `sessions/*.json` | ~117 MB (460 files) | Set `sessions.auto_prune: true, retention_days: 30` |
| `checkpoints/` | ~240 MB | Set `checkpoints.auto_prune: true, max_snapshots: 10` |
| `obscura-bin/` | ~77 MB | Delete (obsolete browser binary) |
| `lsp/` | ~38 MB | Delete (not used from terminal) |
| `video-gen/` | ~520 MB | Archive to `/opt/data/archive/` |
| `gstack/` | ~48 MB | Archive to `/opt/data/archive/` |
| `__pycache__/` (×2,050) | ~50 MB | `find -type d -name __pycache__ -exec rm -rf {} +` |
| `tmp/` | ~83 MB | `rm -rf /opt/data/tmp/*` |
| `brain/raw/` (107 entries) | ~54 MB | Consolidate to ~30 structured entries |

## Root Cause

The Hermes v0.10.0 → v0.20.0 upgrade moved:
- Source code: `/root/hermes-agent/` → `/opt/hermes/` (inside Docker image)
- Data: `/root/hermes-agent/data/` → should be `/opt/hermes/data/` but the volume mount still points to the old path

The running container has mounts from the OLD compose file. The NEW compose file at `/opt/hermes/docker-compose.yml` is correct, but was never used to recreate the container. This is a classic docker-compose drift.

**Fix:** Update the docker-compose.yml with correct paths, then `docker compose up -d --force-recreate`.